### ISSUE TITLE
Mod prevents loading or creating worlds

### ISSUE THREAD

**Issue by niraqw** [MaroonShaded/GildedArmor#12]
When trying to create or load existing worlds with Gilded Armor installed, the game shows the following message:

![image](https://user-images.githubusercontent.com/22210045/135011534-67a9589f-fbbe-4abf-bc4e-b62e4dacb74e.png)

Clicking Safe Mode does nothing. This doesn't occur in version 1.1.2.

Minecraft 1.16.5
Forge 36.2.6
Mods: Gilded Armor Forge 1.16.5 - v1.1.3

**Comment by Baggytrousers27** [comment]
Forge 1.17.1 37.0.73
gildedarmor-forge-1.17.1-1.2.0

[Log](https://pastebin.com/QcN4MUJm)

**Comment by MaroonShaded** [comment]
I didn't see GitHub sorry, I'll publish a new version with a fix asap
