### ISSUE TITLE
[1.16.5-v1.3.3] Broken recipes in the datapack prevent creating or loading worlds.

### ISSUE THREAD

**Issue by Thombias** [MaroonShaded/GildedArmor#13]
Hey there, so i somehow am getting this error now about the datapack in this mod which prevents creating or loading worlds.  I strangely enough didn't get this error before though, it just happens now for unknown reasons, See screenshots from the log here:
![image](https://user-images.githubusercontent.com/46842890/136091430-032e2d1a-ac0e-49d7-9063-3216b0ceb0f7.png)
![image](https://user-images.githubusercontent.com/46842890/136091449-1332e0fe-084e-49d9-b782-8d8b6cdae7c7.png)
I have looked into the mods files in gildedarmor-forge-1.16.5-1.1.3.jar/data/gildedarmor/recipes/ and i've found out that the recipes in the gilded_enderite_xyz_smithing.json files are broken. The tag has a # for some reason, which breaks the recipe/datapack and i like i mentioned above, it makes it impossible to play the game.
The gilded_netherite_xyz_smithing.json files are fine and don't have the # in them.

Can you upload a new file with the # removed from the gilded_enderite_xyz_smithing.json recipes so it can be used by modpacks? That should fix the issue. I'd like to do it myself but whenever i change just a teeny tiny little thing in the mod's .jar file the CurseForge Launcher just straight up removes the file because it is no longer a legit file, or rather, modified in this case.

Thanks in advance!

**Comment by MaroonShaded** [comment]
Oh, my bad! I'll fix this ASAP

**Comment by WeeScottishMan** [comment]
[gildedarmor-forge-1.16.5-1.1.3.zip](https://github.com/MaroonShaded/GildedArmor/files/7303168/gildedarmor-forge-1.16.5-1.1.3.zip)

Fixed it for you :D
