### ISSUE TITLE
Port to 1.18

### ISSUE THREAD

**Issue by Flexz9** [MaroonShaded/GildedArmor#15]
Would it be possible to port to 1.18? As far as I understood of other mods it's not too different from 1.17.

Thank you for this amazing mod!

**Comment by MaroonShaded** [comment]
I'm just waiting for 1.18.1 to release. Do you want it quicker?

**Comment by Flexz9** [comment]
That would be perfect. I was planning to do an update of the server when 1.18.1 drops anyway!

**Comment by Flexz9** [comment]
Meanwhile 1.18.1 has released. Do you have an idea if when you would have time to update? :)

**Comment by MaroonShaded** [comment]
Yeah I know I'm 8 months late I'm sorry but yay? I guess lol
