### ISSUE TITLE
Game is crashing when mining gold 1.16.5

### ISSUE THREAD

**Issue by ItsKandar** [MaroonShaded/GildedArmor#16]
Hi im using your mod in 1.16.5 and the game crash when I mine any gold ore.
Im using the version 1.2.4 for fabric, I tried with and without piglib and it still crashed.

here's the whole crash report if you need it

[crash-2021-12-21_20.54.18-client.txt](https://github.com/MaroonShaded/GildedArmor/files/7757887/crash-2021-12-21_20.54.18-client.txt)

**Comment by MaroonShaded** [comment]
For mod issues using Fabric, please refer to [this repository](https://github.com/MaroonShaded/GildedArmorFabric).
