### ISSUE TITLE
[Suggestion/support] for wardenloot

### ISSUE THREAD

**Issue by AnomalousDeity** [MaroonShaded/GildedArmor#17]
would it be possible to add support for warden loot mod OR the ability to convert the armor back to Normal netherite
because warden loot in order to make the warden set requires a set of netherite armor but doesnt register gilded netherite armor.

**Comment by MaroonShaded** [comment]
Maybe you shouldn't be able to upgrade gilded armor any further. Do you think it's better to add gilded depth-keeper's armor?
