### ISSUE TITLE
Remove the note in the description of the armor

### ISSUE THREAD

**Issue by Telezhka-the-First** [MaroonShaded/GildedArmor#18]
It's all in the title. As for me, this note only obscures the overview of an armor.

**Comment by MaroonShaded** [comment]
You're right. It's like beds saying you can't recolor them. I'll just add that in mod information pages. Thanks for the feedback.

**Comment by MaroonShaded** [comment]
I've removed them starting from the 1.19.2 Forge version. Should I remove them from previous versions too?

**Comment by Federsavo** [comment]
I'm not the original poster but I still play on the previous versions and I would like if you remove it.

**Comment by MaroonShaded** [comment]
I understand, thank you. I'll make a patch for previous versions.
