### ISSUE TITLE
Can colab with Detail Armor Bar mod？

### ISSUE THREAD

**Issue by ioococ** [MaroonShaded/GildedArmor#19]

**Comment by MaroonShaded** [comment]
I was thinking something like this:

![gilded_netherite_detailab_demo1](https://github.com/MaroonShaded/GildedArmor/assets/51722734/707099ec-0cfe-4e29-a0e7-2e57a0f5218a)

![gilded_netherite_detailab_demo2](https://github.com/MaroonShaded/GildedArmor/assets/51722734/c2bb5fc8-c5c6-475e-b3d2-eee300d2d3c4)

**Comment by ioococ** [comment]
so gooood !

**Comment by MaroonShaded** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Detail Armor Bar support](https://trello.com/c/jvhMpejq/2-detail-armor-bar-support)

**Comment by MaroonShaded** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Detail Armor Bar support for 1.20](https://trello.com/c/LhiKbYhN/3-detail-armor-bar-support-for-120)
