### ISSUE TITLE
Newest version seems to crash my server, but works fine in singleplayer.

### ISSUE THREAD

**Issue by Cinderheart** [MaroonShaded/GildedArmor#6]
![crashreport](https://user-images.githubusercontent.com/77930856/118496810-7834d000-b6f2-11eb-9253-d92d9dcc63a4.png)

Here, I think this has something to do with it adding enderite but not having any way to obtain or define it.

**Comment by Cinderheart** [comment]
Nevermind. My modpack has a toooon of other errors cropping up now, there's a good chance that this is just a side effect.

**Comment by MaroonShaded** [comment]
People are also commenting that on CurseForge, so don't worry. I'll fix that

**Comment by MaroonShaded** [comment]
Oh! Checking the code, it's because I'm calling a client-only method, I think. That's why it doesn't work on server. I don't have time today, so I'll fix it tomorrow.
