### ISSUE TITLE
I made a Chinese file for your work

### ISSUE THREAD

**Issue by Moze-Yosel** [MaroonShaded/GildedArmor#7]
[Chinese.zip](https://github.com/MaroonShaded/GildedArmor/files/6603800/Chinese.zip)

**Comment by MaroonShaded** [comment]
Thank you very much! You'll be added to the credits.
I'm curious, could you please explain me why that goes before and in the other three it goes after?

[![Translation](https://user-images.githubusercontent.com/51722734/121512419-99cb6380-c9e1-11eb-8686-932145fd8035.png)](https://github.com/MaroonShaded/GildedArmor/files/6603800/Chinese.zip)
